### ISSUE TITLE
How to change the dense outputs put from colmap into those in dataset.

### ISSUE THREAD

**Issue by tianyilt** [intel-isl/FreeViewSynthesis#11]
Hi! When I tried to test my own image data, I was blocked for the gap between dense file output by Colmap and the downloaded dataset. It seems to be hard for me to make this translation. Could you give me some hits for it? For example, a script. Sincerely thanks.
The output of the colmap is as following.
![image](https://user-images.githubusercontent.com/41582525/98621839-27a77900-2343-11eb-9a56-a687ab126a93.png)
The official output describe can be found [here](https://colmap.github.io/format.html):
+── images
│   +── image1.jpg
│   +── image2.jpg
│   +── ...
+── sparse
│   +── cameras.txt
│   +── images.txt
│   +── points3D.txt
+── stereo
│   +── consistency_graphs
│   │   +── image1.jpg.photometric.bin
│   │   +── image2.jpg.photometric.bin
│   │   +── ...
│   +── depth_maps
│   │   +── image1.jpg.photometric.bin
│   │   +── image2.jpg.photometric.bin
│   │   +── ...
│   +── normal_maps
│   │   +── image1.jpg.photometric.bin
│   │   +── image2.jpg.photometric.bin
│   │   +── ...
│   +── patch-match.cfg
│   +── fusion.cfg
+── fused.ply
+── meshed-poisson.ply
+── meshed-delaunay.ply
+── run-colmap-geometric.sh
+── run-colmap-photometric.sh

**Comment by griegler** [comment]
Unfortunately, I can not share a script yet. But we are in the progress of releasing the code for the Stable View Synthesis project that hopefully will include the scripts. What is missing is rendereing the depthmaps (using pyrender) and computing the overlaps. For the latter the function is already included in `ext/preprocess`.

**Comment by tianyilt** [comment]
Thanks, I try to make the former.

**Comment by tianyilt** [comment]
And congratulation on your new awesome work！
