### ISSUE TITLE
How to obtain consistent image and depthmap size

### ISSUE THREAD

**Issue by whyjay** [intel-isl/FreeViewSynthesis#12]
Hi,  I'm trying to reproduce your preprocessing steps since code that converts colmap output to algorithm input is not provided.
I have two questions.

1) Will the full preprocessing (that converts sequence of images to preprocessed dataset) code available soon?    
2) Colmap changes sizes of images and depth maps while dense reconstruction. (It calls `image_undistorter`). 
But all images and depth maps in your preprocessed datasets have consistent widths and heights.  
How did you preserve the sizes (or compensate size changes)?  

Thank you.

**Comment by griegler** [comment]
1) Most likely not in this repo. But we are working on releasing the code for Stable View Synthesis that hopefully will include the preprocessing scripts. They are compatible with this project.
2) The images do not have the same size? I pad the images to be compatible with the U-Nets (see [here](https://github.com/intel-isl/FreeViewSynthesis/blob/master/exp/exp.py#L64)). Note that the dataset has also to option to have a common `im_size`.

**Comment by whyjay** [comment]
Thank you for the response!
