### ISSUE TITLE
Question about preprocess.cpp

### ISSUE THREAD

**Issue by visonpon** [intel-isl/FreeViewSynthesis#14]
Hi @griegler , in preprocess.cpp [mat3_t K(src_Ks_np.data() + vidx * 3 * 3, 3, 3)](https://github.com/intel-isl/FreeViewSynthesis/blob/d576938f2d8e90b7f7c0536d2b626306dbbea87c/ext/preprocess/preprocess.cpp#L82) , the src_Ks_np'size is (n_views,3,3) but K's size is(3,3), So I wonder if there has problem? 
I also try to do this in python, so i modify this line like  K = (src_Ks_np+vidx * 3 * 3)[0,:3,:3] or  K = (src_Ks_np[vidx]+vidx * 3 * 3), but it didn't work right. Hope you can help, thanks~

**Comment by griegler** [comment]
In `count_nbs` I compute the "overlap" of a target image with the source images. Hence, I need all `K` matrices of the source images. The number of source images is `n_views` in this case and hence, `mat3_t K(src_Ks_np.data() + vidx * 3 * 3, 3, 3)`.

**Comment by visonpon** [comment]
Thanks for your response and explanation and I have written the  `get_sample_map` and` count_nbs` in a python script.
 I would like to upload this if you think is necessary~
