### ISSUE TITLE
IndexError while running exp.py

### ISSUE THREAD

**Issue by avani17101** [intel-isl/FreeViewSynthesis#15]
while running                                                                                                                              
  ``` bash
python exp.py --net rnn_vgg16unet3_gruunet4.64.3 --cmd eval --iter last --eval-dsets tat-subseq --eval-scale 0.5
```
I get the error: IndexError: index 221 is out of bounds for axis 0 with size 0

![Screenshot from 2020-12-12 16-33-24](https://user-images.githubusercontent.com/33591258/101982128-c9e6b380-3c97-11eb-9c77-0222d264927a.png)

I modified my path to point Playground dataset in config and commented truck, M60 and train eval tracks.

**Comment by griegler** [comment]
Could you post your `config.py` and the modified code in `exp.py`.

**Comment by avani17101** [comment]
> Could you post your `config.py` and the modified code in `exp.py`.


Hello, the only change I made is in config.py. Do I need to change in exp.py?
![Screenshot from 2020-12-13 22-17-01](https://user-images.githubusercontent.com/33591258/102018089-f4686780-3d90-11eb-8c22-606ae0cdec10.png)
That is changed path and wanted to run eval only on Playground dataset (downloaded dataset from the repo as given)

**Comment by griegler** [comment]
What is inside of `/home/avani/Desktop/research/datasets`? Does it contain `ibr3d_tat`, if yes, change `tat_root` to `/home/avani/Desktop/research/datasets/ibr3d_tat`.

**Comment by avani17101** [comment]
> What is inside of `/home/avani/Desktop/research/datasets`? Does it contain `ibr3d_tat`, if yes, change `tat_root` to `/home/avani/Desktop/research/datasets/ibr3d_tat`.

Can you clarify the dataset path a bit more. I made `intermediate/Playground` inside` /home/avani/Desktop/research/datasets`

**Comment by avani17101** [comment]
thanks, got it working
