### ISSUE TITLE
Change the camera parameters, but get the same output

### ISSUE THREAD

**Issue by visonpon** [intel-isl/FreeViewSynthesis#16]
Hi @griegler, When I try to modify the `Ks.npy/Rs.npy/ts.npy` for synthesis new view images, the output results are always the same as the original camera parameters' output, hope you  can help, thanks~

**Comment by griegler** [comment]
Can you give a couple more details what you try to achieve and what you tried? I am not sure I fully understand the problem.

**Comment by visonpon** [comment]
I'm sorry that I didn't make it clear, what I want to do is to synthesis a new view image, so I try to modify the camera's parameters and hope that by giving new camera parameters the model can output a new synthesized image that never existed before. But after change the camera parameters, the output didn't have any change
AM I have some misunderstanding about the paper?

**Comment by griegler** [comment]
Note that you also need the depth map in the target view and the overlap to the source views.
You could have a look at the code [here](https://github.com/intel-isl/FreeViewSynthesis/blob/master/data/create_custom_track.py). It is the script I used to create custom tracks.

**Comment by visonpon** [comment]
yeah, the target view is what I want to synthesize, but how to get its depth map before the target view image synthesized since it's a new view that hasn't come out before

**Comment by griegler** [comment]
You render the depth map of the target view from the proxy geometry (mesh reconstructed from the source images).

**Comment by visonpon** [comment]
oh, I got it, Thanks for your patient response~
