### ISSUE TITLE
Questions about the paper

### ISSUE THREAD

**Issue by 07hyx06** [intel-isl/FreeViewSynthesis#19]
Thanks for your great work! 

I have some questions about the Experimental Evaluation Section in the paper:
1. How many source views are used to infer a target view in the training phase?
2. What about the performance on DTU and Tanks and Temples with a few source views (e.g. 5 or 7 views)?

**Comment by griegler** [comment]
> How many source views are used to infer a target view in the training phase?

https://github.com/intel-isl/FreeViewSynthesis/blob/master/exp/exp.py#L391

> What about the performance on DTU and Tanks and Temples with a few source views (e.g. 5 or 7 views)?

I did not use more than 7 source images in the evaluations. There are diminishing returns in this method when using more views (depending on the dataset).
