### ISSUE TITLE
How to get the synthesize images from input images?

### ISSUE THREAD

**Issue by Archger** [intel-isl/FreeViewSynthesis#20]

**Comment by visonpon** [comment]
Just use exp.py

**Comment by 07hyx06** [comment]
Modify the ```self.loss_forward``` function in ```exp.py``` (line 255). Here, the variable ```est``` and ```tgt``` stands for the synthesis view and the ground truth view respectively. You can add some code to save them.

**Comment by z1z9b89** [comment]
Can I output a file in ply format or obj format?
