### ISSUE TITLE
Percetual Loss

### ISSUE THREAD

**Issue by nicksunyang** [intel-isl/FreeViewSynthesis#23]
for midx, mod in enumerate(self.vgg):
            es = mod(es)

>>> for i,mod in enumerate(vgg):
...     if i == 3:
...         print(mod)
... 
ReLU(inplace=True)

I can't understand this，why?

**Comment by griegler** [comment]
Are you refering to [this part of the code](https://github.com/intel-isl/FreeViewSynthesis/blob/master/exp/modules.py#L36-L57)? What do you not understand?

**Comment by nicksunyang** [comment]
Yeah，I suppose mod only represents one layer, eg. i= 3 mod is ReLU.

**Comment by griegler** [comment]
Yes, you can verify via `print(torchvision.models.vgg19().features)`.
