### ISSUE TITLE
co package version

### ISSUE THREAD

**Issue by Cogito2012** [intel-isl/FreeViewSynthesis#25]
Thanks for this great work! 
When I was running the evaluation command, following error was shown in [this line of code](https://github.com/intel-isl/FreeViewSynthesis/blob/33a31ee214a77a2fa074d3a10cedc09803ec2ceb/exp/dataset.py#L30):

```shell
class Dataset(co.mytorch.BaseDataset):
AttributeError: module 'co' has no attribute 'mytorch'

```

It seems that the version of `co` package installed is not correct, since I install it simply by `pip install co`. But what exact `co` package does this repo use? I cannot find any official document about this package.

**Comment by griegler** [comment]
`co` refers to the lib directly in the repo (https://github.com/intel-isl/FreeViewSynthesis/tree/master/co). You do not have to install anything, you can use it as in https://github.com/intel-isl/FreeViewSynthesis/blob/master/exp/exp.py#L11-L12 .
