### ISSUE TITLE
Reconstructed mesh from COLMAP 

### ISSUE THREAD

**Issue by yongsiang-fb** [intel-isl/FreeViewSynthesis#28]
Hi,

Thanks for sharing the preprocessed dataset.

I am wondering if you still have the reconstructed meshes for the dataset produced by COLMAP? Would it be possible to share them?

Thanks a lot.

**Comment by Asherchi** [comment]
I am also have this question, looking forward yours answer.

**Comment by yongsiang-fb** [comment]
It seems the meshes were already in the shared dataset.
