### ISSUE TITLE
Cannot find net_*.params in net_path 

### ISSUE THREAD

**Issue by stevechaw** [intel-isl/FreeViewSynthesis#4]
When I run 
    python exp.py --net rnn_vgg16unet3_gruunet4.64.3 --cmd eval --iter last --eval-dsets tat-subseq --eval-scale 0.5

I got this error:
[2020-10-30/12:22/INFO/mytorch] [EVAL] no network params for iter last

And I add some print, I found in get_net_paths function, the net_root is exp/experiments/tat_nbs5_s0.25_p192_rnn_vgg16unet3_gruunet4.64.3, and in this directory, there is no file named after params, only have one .log file and  one .db file.

How can I fix this problem? 3ks

**Comment by griegler** [comment]
I added a link to the pretrained models and a description how to unpack them in the `README.md`.
