### ISSUE TITLE
Error in evaluation script

### ISSUE THREAD

**Issue by grgkopanas** [intel-isl/FreeViewSynthesis#5]
Hi,

Thanks for uploading the code, I tried to run the evaluation script by following the readme and I got this error:

>>python exp.py --net rnn_vgg16unet3_gruunet4.64.3 --cmd eval --iter last --eval-dsets tat-subseq --eval-scale 0.5
[...]
[2020-10-30/21:28/INFO/mytorch] Eval iter 749999
/home/gkopanas/.conda/envs/freeviewsynthesis/lib/python3.6/site-packages/torch/nn/functional.py:3384: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
Traceback (most recent call last):
  File "exp.py", line 467, in <module>
    worker.do(args, worker_objects)
  File "../co/mytorch.py", line 423, in do
    self.do_cmd(args, worker_objects)
  File "../co/mytorch.py", line 411, in do_cmd
    worker_objects, iters=args.iter, net_root=args.eval_net_root
  File "../co/mytorch.py", line 600, in eval_iters
    self.eval(iter, net, eval_sets)
  File "../co/mytorch.py", line 609, in eval
    self.eval_set(iter, net, eval_set_idx, eval_set, epoch=epoch)
  File "../co/mytorch.py", line 676, in eval_set
    err_str = self.format_err_str(err_items)
  File "../co/mytorch.py", line 546, in format_err_str
    err_list.extend(v.ravel())
AttributeError: 'list' object has no attribute 'ravel'

All the best,
George Kopanas

**Comment by stevechaw** [comment]
Hi there, I fix this by replace
    err_list.extend(v.ravel())
to
    if (np.array(v).ndim > 1):
        err_list.extend(v.ravel())
    else:
        err_list.extend(v)
