### ISSUE TITLE
how to set tat_root in config.py

### ISSUE THREAD

**Issue by tianyilt** [intel-isl/FreeViewSynthesis#6]
Hi, thanks for your great work.
I just want to eval the result by `python exp.py --net rnn_vgg16unet3_gruunet4.64.3 --cmd eval --iter last --eval-dsets tat-subseq --eval-scale 0.5` in **exp** folder.
I'm confused about the following code in config.py:
```
# TODO: adjust path
tat_root = Path("/path/to/colmap_tat/")
```

And I notice that config.tat_root was used in exp.py
```
    def get_train_set_tat(self, dset):
        dense_dir = config.tat_root / dset / "dense"
        print(dense_dir,'------------------------------------------------------------')
        ibr_dir = dense_dir / f"ibr3d_pw_{self.train_scale:.2f}"
        dset = self.get_pw_dataset(
            name=f'tat_{dset.replace("/", "_")}',
            ibr_dir=ibr_dir,
            im_size=None,
            pad_width=16,
            patch=(self.train_patch, self.train_patch),
            n_nbs=self.train_n_nbs,
            nbs_mode=self.train_nbs_mode,
            train=True,
        )
        return dset
```

I'm curious about why exp.py will load **tat_train_sets** when I try to eval the result with the given pretrained model. It seems that the path list in
```
tat_train_sets = [
    "training/Barn",
    "training/Caterpillar",
    "training/Church",
    "training/Courthouse",
    "training/Ignatius",
    "training/Meetingroom",
    "intermediate/Family",
    "intermediate/Francis",
    "intermediate/Horse",
    "intermediate/Lighthouse",
    "intermediate/Panther",
    "advanced/Auditorium",
    "advanced/Ballroom",
    "advanced/Museum",
    "advanced/Temple",
    "advanced/Courtroom",
    "advanced/Palace",
]
```
isn't exist in this rep.

**Comment by griegler** [comment]
In `config.py` change `tat_root = Path("/path/to/colmap_tat/")` to the actual path where you have put the downloaded preprocessed Tanks and Temples data.

**Comment by griegler** [comment]
and if you provide `--cmd eval` as you did, then no train sets will be loaded.

**Comment by tianyilt** [comment]
Thanks, I made it after setting `tat_root = /data/FreeViewSynthesis`.
