### ISSUE TITLE
has no attribute 'get_sampling_map'

### ISSUE THREAD

**Issue by shuochen365** [intel-isl/FreeViewSynthesis#7]
Hi,
 Thank you very much for sharing your code.   But when I run your code, the following error occurs: 

/FreeViewSynthesis/exp/dataset.py", line 165, in base_getitem
    sampling_maps, valid_depth_masks, valid_map_masks = ext.preprocess.get_sampling_map(
AttributeError: module 'ext.preprocess' has no attribute 'get_sampling_map'

 Hope you can help answer, thank you.

**Comment by griegler** [comment]
Did you compile the Python extension as outlined in the readme? 

```
cd ext/preprocess
cmake -DCMAKE_BUILD_TYPE=Release .
make 
```

**Comment by shuochen365** [comment]
yes，I have

[100%] Linking CXX shared module preprocess.cpython-38-x86_64-linux-gnu.so
[100%] Built target preprocess

**Comment by griegler** [comment]
What happens if you run `python -c 'import preprocess'` or `python -c 'import preprocess; dir(preprocess)'` in `ext/preprocess`?

**Comment by shuochen365** [comment]
/ext/preprocess$   python -c 'import preprocess; dir(preprocess)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'preprocess'

**Comment by griegler** [comment]
That indicates that the extension has not been properly build. Maybe you are using a different Python version for building and running?

**Comment by shuochen365** [comment]
How much Python do you use ？ I use python 3.7.9

**Comment by griegler** [comment]
So `python --version` returns `3.7.9`? Given your previous posting

```
[100%] Linking CXX shared module preprocess.cpython-38-x86_64-linux-gnu.so
[100%] Built target preprocess
```

you used Python 3.8 for building the extension. You might need to change the Python interpreter that cmake is using.

**Comment by shuochen365** [comment]
Ok, I will try again. Thank you very much.

**Comment by shuochen365** [comment]
Thank you very much for your kind answer.  My problem has been solved.
